name = "MTKHelpers"
uuid = "2725b469-bb7f-4d1a-ba58-ced332a70bc7"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "0.5.2-DEV"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"

[extensions]
MTKHelpersMakieExt = "CairoMakie"
MTKHelpersMethodOfLinesExt = "MethodOfLines"

[compat]
CairoMakie = "0.11.4"
Chain = "0.5.0"
ComponentArrays = "0.13.10, 0.14, 0.15"
DiffEqBase = "6.130.0"
Distributions = "0.25.106"
DomainSets = "0.6.7, 0.7"
InlineStrings = "1.4.0"
LabelledArrays = "1.15.0"
Logging = "1.6"
LoggingExtras = "1"
MethodOfLines = "0.10.4"
ModelingToolkit = "8.70.0, 9"
NamedArrays = "0.9.8, 0.10"
OrdinaryDiffEq = "6.58.2"
RecursiveArrayTools = "2.38.10, 3"
Requires = "1.3.0"
SciMLBase = "1.98.1, 2"
StaticArrays = "1.9.0"
SymbolicUtils = "1.4.0"
julia = "1.6"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
